apiVersion: v2
name: pmp-test-api
description: A Helm chart for pmp-test-api
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: application
    version: 0.0.3
    repository: https://comfortablynumb.github.io/pmp-helm-charts
