apiVersion: v2
name: application
description: Helm chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: application
    version: 0.0.25
    repository: https://comfortablynumb.github.io/pmp-helm-charts
